# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: alash325/javaant:latest
    permissions:
        id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build
      run: ant -noinput -buildfile build.xml
    - name: Test
      run: ant -lib test/lib/junit.jar -Dtest=AllTests testall
    - uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./build/report/
  
  deploy:
    needs: build
    
    permissions:
      pages: write
      id-token: write
      
    environment:
      name: artifact
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
